---
title: "Gov 50 Final Project"
author: "Julia Poulson"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the midterm election in an effort to determine the relationship between election indicators (gdp, inflation, presidential approval, etc) and election results. I am working through the HPR Tech team on a midterm election prediction model, and I am hoping to use the data acquired through that project to look at relationships between multiple factors and election results for the final project in this course.

## Proposal

In my final project, I will be attempting to see how strongly gas prices correlate to election results using inflation-adjusted gas prices and congressional election data (displaying seats won/lost for each party, as well as the party holding the presidency for each election) from the past 40 years. I predict that gas prices have a strong inverse correlation with the tendency of populations to elect incumbent parties because peoples’ dissatisfaction with high gas prices is often directly aimed at the party in power, regardless of political affiliation. For this to be true, the regression between the amount of seats won by the current presidential party and the price of gas should have a significant negative correlation coefficient. I will also analyze the gas price data against Republican/Democratic seats won in order to see if gas prices are actually more strongly indicative of the party people elect, as opposed to if they choose to vote for the incumbent party. If this regression shows a strong correlation, or if my previous regression shows a positive or non-correlation between gas prices and incumbent party political success, my theory is likely wrong.

Gas Price Data: 
https://www.cnbc.com/2022/04/13/how-much-gas-cost-every-year-since-1978.html

Congressional Election Data:
https://docs.google.com/spreadsheets/d/1IfVf6tRtdyRHWzMCaCmHJyvYBGqEUER5BMeL26knLrQ/edit?usp=sharing
